# Generated by Django 3.2.11 on 2022-01-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=50)),
                ('model_image', models.ImageField(upload_to='')),
                ('create_date', models.DateTimeField(verbose_name='data published')),
            ],
        ),
    ]
