# Generated by Django 3.2.11 on 2022-01-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catimg',
            name='model_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
