# Generated by Django 3.2.11 on 2022-01-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_catimg_model_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(help_text='고양이의 종류를 입력하세요', max_length=50)),
                ('cat_image', models.ImageField(blank=True, upload_to='')),
                ('cat_info', models.TextField(help_text='고양이를 설명해주세요')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='catImg',
        ),
    ]
