# Generated by Django 3.2.11 on 2022-01-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220110_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='cat',
            new_name='cat_name',
        ),
    ]
